//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Метаданные связи EDM

[assembly: EdmRelationshipAttribute("Enterprise", "WB_DRIVER_FK", "DRIVER", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Enterprise.Models.DRIVER), "WAYBILLS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Enterprise.Models.WAYBILLS), true)]
[assembly: EdmRelationshipAttribute("Enterprise", "WB_TCO_FK", "TCO", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Enterprise.Models.TCO), "WAYBILLS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Enterprise.Models.WAYBILLS), true)]

#endregion

namespace Enterprise.Models
{
    #region Контексты
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    public partial class EnterpriseContainer : ObjectContext
    {
        #region Конструкторы
    
        /// <summary>
        /// Инициализирует новый объект EnterpriseContainer, используя строку соединения из раздела "EnterpriseContainer" файла конфигурации приложения.
        /// </summary>
        public EnterpriseContainer() : base("name=EnterpriseContainer", "EnterpriseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EnterpriseContainer.
        /// </summary>
        public EnterpriseContainer(string connectionString) : base(connectionString, "EnterpriseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Инициализация нового объекта EnterpriseContainer.
        /// </summary>
        public EnterpriseContainer(EntityConnection connection) : base(connection, "EnterpriseContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Разделяемые методы
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Свойства ObjectSet
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<DRIVER> DRIVER
        {
            get
            {
                if ((_DRIVER == null))
                {
                    _DRIVER = base.CreateObjectSet<DRIVER>("DRIVER");
                }
                return _DRIVER;
            }
        }
        private ObjectSet<DRIVER> _DRIVER;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<TCO> TCO
        {
            get
            {
                if ((_TCO == null))
                {
                    _TCO = base.CreateObjectSet<TCO>("TCO");
                }
                return _TCO;
            }
        }
        private ObjectSet<TCO> _TCO;
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        public ObjectSet<WAYBILLS> WAYBILLS
        {
            get
            {
                if ((_WAYBILLS == null))
                {
                    _WAYBILLS = base.CreateObjectSet<WAYBILLS>("WAYBILLS");
                }
                return _WAYBILLS;
            }
        }
        private ObjectSet<WAYBILLS> _WAYBILLS;

        #endregion
        #region Методы AddTo
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet DRIVER. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToDRIVER(DRIVER dRIVER)
        {
            base.AddObject("DRIVER", dRIVER);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet TCO. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToTCO(TCO tCO)
        {
            base.AddObject("TCO", tCO);
        }
    
        /// <summary>
        /// Устаревший метод для добавления новых объектов в набор EntitySet WAYBILLS. Взамен можно использовать метод .Add связанного свойства ObjectSet&lt;T&gt;.
        /// </summary>
        public void AddToWAYBILLS(WAYBILLS wAYBILLS)
        {
            base.AddObject("WAYBILLS", wAYBILLS);
        }

        #endregion
    }
    

    #endregion
    
    #region Сущности
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Enterprise", Name="DRIVER")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DRIVER : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта DRIVER.
        /// </summary>
        /// <param name="nAME">Исходное значение свойства NAME.</param>
        /// <param name="dRIVER_ID">Исходное значение свойства DRIVER_ID.</param>
        public static DRIVER CreateDRIVER(global::System.String nAME, global::System.Int32 dRIVER_ID)
        {
            DRIVER dRIVER = new DRIVER();
            dRIVER.NAME = nAME;
            dRIVER.DRIVER_ID = dRIVER_ID;
            return dRIVER;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String NAME
        {
            get
            {
                return _NAME;
            }
            set
            {
                OnNAMEChanging(value);
                ReportPropertyChanging("NAME");
                _NAME = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("NAME");
                OnNAMEChanged();
            }
        }
        private global::System.String _NAME;
        partial void OnNAMEChanging(global::System.String value);
        partial void OnNAMEChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DRIVER_ID
        {
            get
            {
                return _DRIVER_ID;
            }
            set
            {
                if (_DRIVER_ID != value)
                {
                    OnDRIVER_IDChanging(value);
                    ReportPropertyChanging("DRIVER_ID");
                    _DRIVER_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DRIVER_ID");
                    OnDRIVER_IDChanged();
                }
            }
        }
        private global::System.Int32 _DRIVER_ID;
        partial void OnDRIVER_IDChanging(global::System.Int32 value);
        partial void OnDRIVER_IDChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Enterprise", "WB_DRIVER_FK", "WAYBILLS")]
        public EntityCollection<WAYBILLS> WAYBILLS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WAYBILLS>("Enterprise.WB_DRIVER_FK", "WAYBILLS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WAYBILLS>("Enterprise.WB_DRIVER_FK", "WAYBILLS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Enterprise", Name="TCO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TCO : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта TCO.
        /// </summary>
        /// <param name="sTATE_NUMBER">Исходное значение свойства STATE_NUMBER.</param>
        public static TCO CreateTCO(global::System.String sTATE_NUMBER)
        {
            TCO tCO = new TCO();
            tCO.STATE_NUMBER = sTATE_NUMBER;
            return tCO;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String STATE_NUMBER
        {
            get
            {
                return _STATE_NUMBER;
            }
            set
            {
                if (_STATE_NUMBER != value)
                {
                    OnSTATE_NUMBERChanging(value);
                    ReportPropertyChanging("STATE_NUMBER");
                    _STATE_NUMBER = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("STATE_NUMBER");
                    OnSTATE_NUMBERChanged();
                }
            }
        }
        private global::System.String _STATE_NUMBER;
        partial void OnSTATE_NUMBERChanging(global::System.String value);
        partial void OnSTATE_NUMBERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AT_ID
        {
            get
            {
                return _AT_ID;
            }
            set
            {
                OnAT_IDChanging(value);
                ReportPropertyChanging("AT_ID");
                _AT_ID = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("AT_ID");
                OnAT_IDChanged();
            }
        }
        private global::System.String _AT_ID;
        partial void OnAT_IDChanging(global::System.String value);
        partial void OnAT_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARK
        {
            get
            {
                return _MARK;
            }
            set
            {
                OnMARKChanging(value);
                ReportPropertyChanging("MARK");
                _MARK = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MARK");
                OnMARKChanged();
            }
        }
        private global::System.String _MARK;
        partial void OnMARKChanging(global::System.String value);
        partial void OnMARKChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MODEL
        {
            get
            {
                return _MODEL;
            }
            set
            {
                OnMODELChanging(value);
                ReportPropertyChanging("MODEL");
                _MODEL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MODEL");
                OnMODELChanged();
            }
        }
        private global::System.String _MODEL;
        partial void OnMODELChanging(global::System.String value);
        partial void OnMODELChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> WEIGHT
        {
            get
            {
                return _WEIGHT;
            }
            set
            {
                OnWEIGHTChanging(value);
                ReportPropertyChanging("WEIGHT");
                _WEIGHT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("WEIGHT");
                OnWEIGHTChanged();
            }
        }
        private Nullable<global::System.Int32> _WEIGHT;
        partial void OnWEIGHTChanging(Nullable<global::System.Int32> value);
        partial void OnWEIGHTChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Enterprise", "WB_TCO_FK", "WAYBILLS")]
        public EntityCollection<WAYBILLS> WAYBILLS
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<WAYBILLS>("Enterprise.WB_TCO_FK", "WAYBILLS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<WAYBILLS>("Enterprise.WB_TCO_FK", "WAYBILLS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// Нет доступной документации по метаданным.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Enterprise", Name="WAYBILLS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class WAYBILLS : EntityObject
    {
        #region Фабричный метод
    
        /// <summary>
        /// Создание нового объекта WAYBILLS.
        /// </summary>
        /// <param name="wAYBILL_ID">Исходное значение свойства WAYBILL_ID.</param>
        /// <param name="tCO">Исходное значение свойства TCO.</param>
        public static WAYBILLS CreateWAYBILLS(global::System.Int32 wAYBILL_ID, global::System.String tCO)
        {
            WAYBILLS wAYBILLS = new WAYBILLS();
            wAYBILLS.WAYBILL_ID = wAYBILL_ID;
            wAYBILLS.TCO = tCO;
            return wAYBILLS;
        }

        #endregion
        #region Свойства-примитивы
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 WAYBILL_ID
        {
            get
            {
                return _WAYBILL_ID;
            }
            set
            {
                if (_WAYBILL_ID != value)
                {
                    OnWAYBILL_IDChanging(value);
                    ReportPropertyChanging("WAYBILL_ID");
                    _WAYBILL_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("WAYBILL_ID");
                    OnWAYBILL_IDChanged();
                }
            }
        }
        private global::System.Int32 _WAYBILL_ID;
        partial void OnWAYBILL_IDChanging(global::System.Int32 value);
        partial void OnWAYBILL_IDChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TCO
        {
            get
            {
                return _TCO;
            }
            set
            {
                OnTCOChanging(value);
                ReportPropertyChanging("TCO");
                _TCO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TCO");
                OnTCOChanged();
            }
        }
        private global::System.String _TCO;
        partial void OnTCOChanging(global::System.String value);
        partial void OnTCOChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DRIVER
        {
            get
            {
                return _DRIVER;
            }
            set
            {
                OnDRIVERChanging(value);
                ReportPropertyChanging("DRIVER");
                _DRIVER = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DRIVER");
                OnDRIVERChanged();
            }
        }
        private Nullable<global::System.Int32> _DRIVER;
        partial void OnDRIVERChanging(Nullable<global::System.Int32> value);
        partial void OnDRIVERChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FUEL_GIVEN
        {
            get
            {
                return _FUEL_GIVEN;
            }
            set
            {
                OnFUEL_GIVENChanging(value);
                ReportPropertyChanging("FUEL_GIVEN");
                _FUEL_GIVEN = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FUEL_GIVEN");
                OnFUEL_GIVENChanged();
            }
        }
        private Nullable<global::System.Int16> _FUEL_GIVEN;
        partial void OnFUEL_GIVENChanging(Nullable<global::System.Int16> value);
        partial void OnFUEL_GIVENChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int16> FUEL_LOST
        {
            get
            {
                return _FUEL_LOST;
            }
            set
            {
                OnFUEL_LOSTChanging(value);
                ReportPropertyChanging("FUEL_LOST");
                _FUEL_LOST = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FUEL_LOST");
                OnFUEL_LOSTChanged();
            }
        }
        private Nullable<global::System.Int16> _FUEL_LOST;
        partial void OnFUEL_LOSTChanging(Nullable<global::System.Int16> value);
        partial void OnFUEL_LOSTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MILEAGE_START
        {
            get
            {
                return _MILEAGE_START;
            }
            set
            {
                OnMILEAGE_STARTChanging(value);
                ReportPropertyChanging("MILEAGE_START");
                _MILEAGE_START = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MILEAGE_START");
                OnMILEAGE_STARTChanged();
            }
        }
        private Nullable<global::System.Int32> _MILEAGE_START;
        partial void OnMILEAGE_STARTChanging(Nullable<global::System.Int32> value);
        partial void OnMILEAGE_STARTChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MILEAGE_FINISH
        {
            get
            {
                return _MILEAGE_FINISH;
            }
            set
            {
                OnMILEAGE_FINISHChanging(value);
                ReportPropertyChanging("MILEAGE_FINISH");
                _MILEAGE_FINISH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MILEAGE_FINISH");
                OnMILEAGE_FINISHChanged();
            }
        }
        private Nullable<global::System.Int32> _MILEAGE_FINISH;
        partial void OnMILEAGE_FINISHChanging(Nullable<global::System.Int32> value);
        partial void OnMILEAGE_FINISHChanged();
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> STATUS
        {
            get
            {
                return _STATUS;
            }
            set
            {
                OnSTATUSChanging(value);
                ReportPropertyChanging("STATUS");
                _STATUS = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("STATUS");
                OnSTATUSChanged();
            }
        }
        private Nullable<global::System.Int32> _STATUS;
        partial void OnSTATUSChanging(Nullable<global::System.Int32> value);
        partial void OnSTATUSChanged();

        #endregion
    
        #region Свойства навигации
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Enterprise", "WB_DRIVER_FK", "DRIVER")]
        public DRIVER DRIVER1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DRIVER>("Enterprise.WB_DRIVER_FK", "DRIVER").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DRIVER>("Enterprise.WB_DRIVER_FK", "DRIVER").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<DRIVER> DRIVER1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<DRIVER>("Enterprise.WB_DRIVER_FK", "DRIVER");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<DRIVER>("Enterprise.WB_DRIVER_FK", "DRIVER", value);
                }
            }
        }
    
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Enterprise", "WB_TCO_FK", "TCO")]
        public TCO TCO1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TCO>("Enterprise.WB_TCO_FK", "TCO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TCO>("Enterprise.WB_TCO_FK", "TCO").Value = value;
            }
        }
        /// <summary>
        /// Нет доступной документации по метаданным.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TCO> TCO1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TCO>("Enterprise.WB_TCO_FK", "TCO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TCO>("Enterprise.WB_TCO_FK", "TCO", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
